version: '3'

networks:
    apartment-online-market-system:
        driver: bridge

services:

    db_market:
        container_name: db_market
        image: mariadb:10.8.2
        restart: always
        ports:
            - "3305:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: apartment_online_market
        volumes:
            - './volumes/database/mysql:/var/lib/mysql'
        networks:
            - apartment-online-market-system

    redis:
        image: redis:latest
        hostname: redis
        container_name: redis_cdcn
        restart: always
        volumes:
            - ./volumes/redis/data:/data
        ports:
            - "6378:6379"
        networks:
            - apartment-online-market-system

#    market-service:
#        hostname: market-service
#        container_name: market-service
#        image: market-service:latest
#        restart: always
#        build:
#            context: ./
#        ports:
#            - "9090:9090"
#        environment:
#            DATABASE_HOST: db_market
#            MARIADB_PORT_NUMBER: 3306
#            REDIS_HOST: redis
#            REDIS_PORT: 6379
#            LOGSTASH_HOST_PORT: logstash:5044
#        links:
#            - db_market
#        depends_on:
#            - db_market
#            - redis
#        networks:
#            - ${GLOBAL_NETWORK}