version: '3.9'

networks:
    apartment-online-market-system:
        driver: bridge

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
        container_name: elasticsearch
        restart: unless-stopped
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: single-node
            xpack.security.enabled: false
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        healthcheck:
            test: "curl -f http://localhost:9200 || exit 1"
        networks:
            - ${GLOBAL_NETWORK}

    logstash:
        image: docker.elastic.co/logstash/logstash:7.17.4
        container_name: logstash
        restart: unless-stopped
        ports:
            - "5044:5044"
        environment:
            ELASTICSEARCH_HOST: http://elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - ./logstash/pipeline:/usr/share/logstash/pipeline/
        depends_on:
            - elasticsearch
        healthcheck:
            test: "curl -f http://localhost:5044 || exit 1"
        networks:
            - ${GLOBAL_NETWORK}

    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.4
        container_name: kibana
        restart: unless-stopped
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
        depends_on:
            - elasticsearch
        healthcheck:
            test: "curl -f http://localhost:5601 || exit 1"
        networks:
            - ${GLOBAL_NETWORK}

    db_market:
        container_name: db_market
        image: mariadb:latest
        restart: always
        ports:
            - "3307:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: apartment_online_market
        volumes:
            - './volumes/database/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK}

    redis:
        image: redis:latest
        hostname: redis
        container_name: pds_redis
        restart: always
        volumes:
            - ./volumes/redis/data:/data
        ports:
            - "6379:6379"
        networks:
            - ${GLOBAL_NETWORK}

    market-service:
        hostname: market-service
        container_name: market-service
        image: market-service:latest
        restart: always
        build:
            context: ./
        ports:
            - "9090:9090"
        environment:
            DATABASE_HOST: db_market
            MARIADB_PORT_NUMBER: 3306
            REDIS_HOST: redis
            REDIS_PORT: 6379
            LOGSTASH_HOST_PORT: logstash:5044
        links:
            - db_market
        depends_on:
            - db_market
            - redis
        networks:
            - ${GLOBAL_NETWORK}

#    sonarqube:
#        hostname: sonarqube
#        container_name: sonarqube
#        image: sonarqube
#        ports:
#            - "10000:9000"
#            - "10092:9092"
#        networks:
#            - ${GLOBAL_NETWORK}