
server:
    port: 9090

spring:
    application:
        name: apartment-online-market
    profiles:
        active: dev

application:
    security:
        authentication:
            access-token-validity-in-seconds: 7200
            refresh-token-validity-in-seconds: 43200